# Generated by Django 3.2.3 on 2021-05-23 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Bookmark Category',
                'verbose_name_plural': 'Bookmarks Categories',
            },
        ),
        migrations.CreateModel(
            name='BookmarkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_title', models.CharField(max_length=255, verbose_name='Title')),
                ('bookmark_uri', models.CharField(max_length=255, unique=True, verbose_name='URI')),
                ('bookmark_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('bookmark_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('bookmark_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('bookmark_favorite', models.BooleanField(default='False', verbose_name='Favorite')),
                ('bookmark_status', models.CharField(choices=[('draft', 'Private'), ('published', 'Public')], default='draft', max_length=12, verbose_name='Status')),
                ('bookmark_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('bookmark_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmark.bookmarkcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ('bookmark_title',),
            },
        ),
    ]
