# Generated by Django 3.2.3 on 2021-05-23 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Category')),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Posts Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Title')),
                ('blog_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('blog_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('blog_picture', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Head picture')),
                ('blog_content', models.TextField(verbose_name='Texte')),
                ('blog_file', models.FileField(blank=True, null=True, upload_to='blog', verbose_name='File')),
                ('blog_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('blog_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('seo_title', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='Seo title')),
                ('seo_description', models.SlugField(blank=True, max_length=165, null=True, unique=True, verbose_name='Seo description')),
                ('blog_favorite', models.BooleanField(default='False', verbose_name='Favorite')),
                ('blog_status', models.CharField(choices=[('draft', 'Private'), ('published', 'Public')], default='draft', max_length=12, verbose_name='Status')),
                ('blog_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('blog_created',),
            },
        ),
    ]
