# Generated by Django 3.2.3 on 2021-05-23 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Device Category',
                'verbose_name_plural': 'Devices Categories',
            },
        ),
        migrations.CreateModel(
            name='DevicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('device_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('device_licence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Licence')),
                ('device_bridge', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bridge')),
                ('device_system', models.CharField(blank=True, max_length=255, null=True, verbose_name='System')),
                ('device_utility', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utility')),
                ('device_HDD', models.CharField(blank=True, max_length=255, null=True, verbose_name='HDD')),
                ('device_IP_rj45', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Rj45')),
                ('device_MAC_rj45', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC Rj45')),
                ('device_IP_wifi', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP WiFi')),
                ('device_MAC_wifi', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC WiFi')),
                ('device_RAM', models.CharField(blank=True, max_length=255, null=True, verbose_name='RAM')),
                ('device_SSD', models.CharField(blank=True, max_length=255, null=True, verbose_name='SSD')),
                ('device_favorite', models.BooleanField(default='False', verbose_name='Favorite')),
                ('device_status', models.CharField(choices=[('draft', 'Private'), ('published', 'Public')], default='private', max_length=12, verbose_name='Status')),
                ('device_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('device_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.devicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ('device_brand',),
            },
        ),
    ]
